/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoskaique.continuada1;

import java.awt.Color;
import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Kaique
 */
public class Tela extends javax.swing.JFrame {

    Cpu cpu1 = new Cpu();
    Memoria memoria1 = new Memoria();
    Disco disco1 = new Disco();
    
    void atualizarCpu(Cpu algumCpu, Double algumValor){
        if(algumCpu.maximo < algumValor){
            algumCpu.maximo = algumValor;
        }
        if(algumCpu.minimo > algumValor){
            algumCpu.minimo = algumValor;
        }
        algumCpu.media = (algumCpu.maximo + algumCpu.minimo) / 2;
    }
    void atualizarDisco(Disco algumDisco, Double algumValor){
        if(algumDisco.maximo < algumValor){
            algumDisco.maximo = algumValor;
        }
        if(algumDisco.minimo > algumValor){
            algumDisco.minimo = algumValor;
        }
        algumDisco.media = (algumDisco.maximo + algumDisco.minimo) / 2;
    }
    void atualizarMemoria(Memoria algumMemoria, Integer algumValor){
        if(algumMemoria.maximo < algumValor){
            algumMemoria.maximo = algumValor;
        }
        if(algumMemoria.minimo > algumValor){
            algumMemoria.minimo = algumValor;
        }
        algumMemoria.media = (algumMemoria.maximo + algumMemoria.minimo) /2.0;
    }
    
    
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgrCpu = new javax.swing.JProgressBar();
        pgrDisco = new javax.swing.JProgressBar();
        pgrMemoria = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLeitura = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDisco = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        taCpu = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        taMemoria = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CPU");

        jLabel2.setText("Memoria");

        jLabel3.setText("Disco");

        btnLeitura.setText("Fazer leitura dos dados");
        btnLeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeituraActionPerformed(evt);
            }
        });

        taDisco.setColumns(20);
        taDisco.setRows(5);
        jScrollPane2.setViewportView(taDisco);

        taCpu.setColumns(20);
        taCpu.setRows(5);
        jScrollPane3.setViewportView(taCpu);

        taMemoria.setColumns(20);
        taMemoria.setRows(5);
        jScrollPane4.setViewportView(taMemoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pgrCpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(btnLeitura, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(pgrMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pgrDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                        .addComponent(jScrollPane4))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgrCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pgrDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgrMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnLeitura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeituraActionPerformed
        pgrCpu.setStringPainted(true);
        pgrCpu.setForeground(Color.black);
        pgrCpu.setMaximum(5);
        
        pgrDisco.setStringPainted(true);
        pgrDisco.setForeground(Color.blue);
        pgrDisco.setMaximum(100);
        
        pgrMemoria.setStringPainted(true);
        pgrMemoria.setForeground(Color.green);
        pgrMemoria.setMaximum(8000);
        
        Double cpu = ThreadLocalRandom.current().nextDouble(1.4,4.6);
        atualizarCpu(cpu1, cpu);
        taCpu.setText(String.format("Maximo CPU registrado: %.1f\n"
                + "Minimo CPU registrado: %.1f\n"
                + "Média CPU registrado: %.2f", cpu1.maximo, cpu1.minimo, cpu1.media));
     
        Integer memoria = ThreadLocalRandom.current().nextInt(1000,8000);
        atualizarMemoria(memoria1, memoria);
        taMemoria.setText(String.format("Maximo memoria registrado: %d\n"
                + "Minimo memoria registrado: %d\n"
                + "Media memoria registrado: %.2f", memoria1.maximo, memoria1.minimo, memoria1.media));
        
        Double disco = ThreadLocalRandom.current().nextDouble(0,100);
        atualizarDisco(disco1, disco);
        taDisco.setText(String.format("Maximo Disco registrado: %.1f\n"
                + "Minimo Disco registrado: %.1f\n"
                + "Média Disco registrado: %.2f", disco1.maximo, disco1.minimo, disco1.media));
        
        pgrCpu.setString(String.format("Uso da CPU em Ghz: %.1f GHz", cpu));
        pgrCpu.setValue((int) Math.round(cpu));
        pgrDisco.setString(String.format("Uso do disco em porcentagem: %.2f", disco));
        pgrDisco.setValue((int) Math.round(disco));
        pgrMemoria.setString(String.format("Uso da memoria em MB: %d MB", memoria));
        pgrMemoria.setValue(memoria);
    }//GEN-LAST:event_btnLeituraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeitura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JProgressBar pgrCpu;
    private javax.swing.JProgressBar pgrDisco;
    private javax.swing.JProgressBar pgrMemoria;
    private javax.swing.JTextArea taCpu;
    private javax.swing.JTextArea taDisco;
    private javax.swing.JTextArea taMemoria;
    // End of variables declaration//GEN-END:variables
}
